/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiApkChunkRouteImport } from './routes/api/apk/chunk'
import { Route as ApiApkStartRouteImport } from './routes/api/apk/start'
import { Route as ApiApkJobIdDownloadRouteImport } from './routes/api/apk/$jobId/download'
import { Route as ApiApkJobIdStatusRouteImport } from './routes/api/apk/$jobId/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkChunkRoute = ApiApkChunkRouteImport.update({
  id: '/api/apk/chunk',
  path: '/api/apk/chunk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkStartRoute = ApiApkStartRouteImport.update({
  id: '/api/apk/start',
  path: '/api/apk/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkJobIdDownloadRoute = ApiApkJobIdDownloadRouteImport.update({
  id: '/api/apk/$jobId/download',
  path: '/api/apk/$jobId/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkJobIdStatusRoute = ApiApkJobIdStatusRouteImport.update({
  id: '/api/apk/$jobId/status',
  path: '/api/apk/$jobId/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/apk/chunk': typeof ApiApkChunkRoute
  '/api/apk/start': typeof ApiApkStartRoute
  '/api/apk/$jobId/download': typeof ApiApkJobIdDownloadRoute
  '/api/apk/$jobId/status': typeof ApiApkJobIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/apk/chunk': typeof ApiApkChunkRoute
  '/api/apk/start': typeof ApiApkStartRoute
  '/api/apk/$jobId/download': typeof ApiApkJobIdDownloadRoute
  '/api/apk/$jobId/status': typeof ApiApkJobIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/api/apk/chunk': typeof ApiApkChunkRoute
  '/api/apk/start': typeof ApiApkStartRoute
  '/api/apk/$jobId/download': typeof ApiApkJobIdDownloadRoute
  '/api/apk/$jobId/status': typeof ApiApkJobIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/apk/chunk'
    | '/api/apk/start'
    | '/api/apk/$jobId/download'
    | '/api/apk/$jobId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/apk/chunk'
    | '/api/apk/start'
    | '/api/apk/$jobId/download'
    | '/api/apk/$jobId/status'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/api/apk/chunk'
    | '/api/apk/start'
    | '/api/apk/$jobId/download'
    | '/api/apk/$jobId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  ApiApkChunkRoute: typeof ApiApkChunkRoute
  ApiApkStartRoute: typeof ApiApkStartRoute
  ApiApkJobIdDownloadRoute: typeof ApiApkJobIdDownloadRoute
  ApiApkJobIdStatusRoute: typeof ApiApkJobIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk/chunk': {
      id: '/api/apk/chunk'
      path: '/api/apk/chunk'
      fullPath: '/api/apk/chunk'
      preLoaderRoute: typeof ApiApkChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk/start': {
      id: '/api/apk/start'
      path: '/api/apk/start'
      fullPath: '/api/apk/start'
      preLoaderRoute: typeof ApiApkStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk/$jobId/download': {
      id: '/api/apk/$jobId/download'
      path: '/api/apk/$jobId/download'
      fullPath: '/api/apk/$jobId/download'
      preLoaderRoute: typeof ApiApkJobIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk/$jobId/status': {
      id: '/api/apk/$jobId/status'
      path: '/api/apk/$jobId/status'
      fullPath: '/api/apk/$jobId/status'
      preLoaderRoute: typeof ApiApkJobIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  ApiApkChunkRoute: ApiApkChunkRoute,
  ApiApkStartRoute: ApiApkStartRoute,
  ApiApkJobIdDownloadRoute: ApiApkJobIdDownloadRoute,
  ApiApkJobIdStatusRoute: ApiApkJobIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
